# This .travis.yml is modified from pandoc's
language: generic
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack
matrix:
  include:
  - sudo: false
    addons:
      apt:
        packages:
          - ghc-8.0.1
        sources:
          - hvr-ghc
  - os: osx
install:
  # Download and unpack the stack executable
  - export PATH=$PATH:$HOME/.local/bin
  - mkdir -p ~/.local/bin
  - |
    if [ `uname` = "Darwin" ]
    then
      curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
script:
  # clone from git
  - git clone https://github.com/jgm/pandoc
  - cd pandoc
  - git submodule update --init
  # build
  - stack setup
  - stack build
  # zip binary
  - HASH=$(git rev-parse HEAD)
  - |
    if [[ `uname` == "Darwin" ]]; then
      filename=pandoc-osx-$HASH
    else
      filename=pandoc-amd64-$HASH
    fi
  - cd ..
  - mkdir -p $filename
  - mv "$(find pandoc/.stack-work/install -type f -iname 'pandoc')" $filename
  - zip $filename.zip $filename/pandoc
  # cleanup and move to dist/
  - rm -rf $filename/pandoc
  - mkdir -p dist && mv $filename/pandoc dist/
  # debug
  - $filename/pandoc -v
after_success:
  # create git tag if it's a cron job and not osx (avoid creating git tag twice)
  - |
    if [[ $TRAVIS_EVENT_TYPE == 'cron' ]] && [[ `uname` != "Darwin" ]]; then
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      export GIT_TAG="hash-$HASH"
      echo -n $HASH > version
      git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
      git push --quiet https://$GH_TOKEN_SECURE@github.com/pandoc-extras/pandoc-nightly $GIT_TAG > /dev/null 2>&1
    fi
  # download Windows' nightly from appveyor if is git tag and on Linux
  - |
    if [[ ! -z "$TRAVIS_TAG" ]] && [[ `uname` != "Darwin" ]]; then
      wget 'https://ci.appveyor.com/api/projects/jgm/pandoc/artifacts/windows/pandoc.msi?branch=master' -O pandoc.msi
      mv pandoc.msi dist/$filename.msi
      wget 'https://ci.appveyor.com/api/projects/jgm/pandoc/artifacts/windows/pandoc.zip?branch=master' -O pandoc.zip
      mv pandoc.zip dist/$filename.zip
    fi
  # debug
  - ls -l dist/
deploy:
  provider: releases
  api_key: "$GH_TOKEN_SECURE"
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: PDNr60bZ/drP2nEkW+8mP9DNPONjElxMrxLSsVtXcDLJbDZPmyFahgiHmYERYiUGXQmzuyQbqQNBydFnHUbeRdZ+owLGzTIv8RzZ1SX+7OKZTwc38cJV3nWq3/F57DXsI32IW21RU1JN0HjCi33X4pDlrz597D78LKS3wRAREgxYMcq1FO+GtQ8B7NdLgFni0g94GiIUOyDoAut1yh43V7LoMtt6izQFJFyENUsaHl6xhhdxBoE6qnNhwP+CxscsCf+keezwCFgjuV+cwmxDhspY5Kx/bPfN0c2/Dwgv/nq+JjsbvVYJUjg/gHvg2dlwkGZKXIn8YmI492UwYxSOJ3TgLktdEgrkjRDPGwRvGpkqkZcZg65BEaTNzb/mj+kqd1sGo3NAfuDP8ArqJrYM2G4qfD2yIDKsFSMnIOH+6g6jmTEVPQt9yA2a3ZyUrXzdgs2i/AtsmUB4YYWHcIjcsjmdGZm6CgG3BMIMUmNuWZk9Ad3YEibd6raZ52RuTkICm0UQjCckg4QG10gS1ZYTTLyJle8f2HWxZZixBGfJQMmJsfn8jFoGsl9SKIseQ3VtEnmsHXSqW9tADFQ9+3n7wiCe+3mUaBVbKhKs6LCEf+oHi/nnkOSbPePdd43gBx3u85dww7jwoE5zDU22zWEBTa3wLztZfHAut8BQ5bYIeXw=
