# This .travis.yml is modified from pandoc's at https://github.com/jgm/pandoc/blob/master/.travis.yml
language: generic
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack
matrix:
  include:
  - sudo: false
    dist: trusty
    addons:
      apt:
        packages:
          - ghc-8.0.2
        sources:
          - hvr-ghc

before_install:
  
  # pandoc-nightly version
  - |
    printf "%s: %s\n" "pandoc-nightly version" "0.2.2"

install:
  
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=$PATH:$HOME/.local/bin

before_script:
  
  # clone from git
  - git clone https://github.com/jgm/pandoc
  - cd pandoc
  - git submodule update --init

  # get the current commit hash of pandoc
  - HASH=$(git rev-parse --short HEAD)
  
  # filename
  - filename=pandoc-amd64-$HASH
  
script:
  
  # build
  - stack setup
  - stack build --flag 'pandoc:embed_data_files'
  - cd ..
  
  # path to the pandoc executable
  - path2pandoc="$(find pandoc/.stack-work/install -type f -iname 'pandoc')"
  
  # debug
  - $path2pandoc -v

after_success:
  
  # zip pandoc binary
  - |
     mkdir -p ./appdir/usr/bin
     mv $filename ./appdir/usr/bin
     
 
 # debug
  - ls -l dist/

